spring:
  datasource:
    url: ${{ secrets.DB_ENDPOINT }}
    username: admin
    password: twotwo22
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cloud:
    openfeign:
      client:
        config:
          githubClient:
            url: localhost:8081
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${{ secrets.OAUTH_CLIENT_ID_GITHUB }}
            client-secret: ${{ secrets.OAUTH_CLIENT_SECRET_GITHUB }}

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkKZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK
cloud:
  aws:
    s3:
      bucket: twotwo-bucket
    credentials:
      access-key: ${{ secrets.AWS_ACCESS_KEY }}
      secret-key: ${{ secrets.AWS_SECRET_KEY }}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazons:
        util:
          EC2MetadataUtils: ERROR

