server:
  port: 8080

spring:
  datasource:
    url: masking
    username: admin
    password: twotwo22
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cloud:
    openfeign:
      client:
        config:
          githubClient:
            url: localhost:8081
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: masking
            client-secret: masking
  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkKZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK
cloud:
  aws:
    s3:
      bucket: twotwo-bucket
    credentials:
      access-key: masking
      secret-key: masking
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazons:
        util:
          EC2MetadataUtils: ERROR

feign:
  community: localhost:8081
  github: localhost:8082
  news: localhost:8083

